services:
  backend-api:
    build: .
    image: backend-api-image
    container_name: backend-api-container
    environment:
      - MONGO_URI=mongodb://root:pass-123@mongodb:27017/book-store?authSource=admin
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
    networks:
      - backend-api-network

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass-123
      - MONGO_INITDB_DATABASE=book-store
    ports:
      - '27017:27017'
    networks:
      - backend-api-network
    volumes:
      - mongodb-volume:/data/db

networks:
  backend-api-network:
    driver: bridge

volumes:
  mongodb-volume:
